export const GET_ALL_PROJECT = "GetAllProjects";
export const GETPROJECTS_FORMAINPAGE = "GetProjectsForMainPage"
export const GETALL_PROJECTS ="GetAllProjects"
export const GETALL_CATEGORIES = "GetAllProjectCategories"
export const CREATE_NEW_PROJECT="CreateNewProject"
export const DELETE_PROJECT_BY_ID= "DeleteProjectById"
export const UPDATE_PROJECT="UpdateProject"
export const ADD_UPDATE_CATEGORY ="AddUpdateCategory"
export const DELETE_CATEGORY_BY_ID= "DeleteCategoryById"
export const GET_ALL_QURIES = "GetAllQuries";
